const TOPICS = [
  {
    id: "campus",
    name: "校园学习",
    en: "Campus",
    color: "#216b78",
    soft: "#e5f2f4",
    icon: "graduation-cap",
  },
  {
    id: "city",
    name: "城市环境",
    en: "City & Nature",
    color: "#267257",
    soft: "#e7f3ec",
    icon: "building-2",
  },
  {
    id: "health",
    name: "健康运动",
    en: "Health & Sports",
    color: "#c6543b",
    soft: "#fbece8",
    icon: "heart-pulse",
  },
  {
    id: "culture",
    name: "文化旅行",
    en: "Culture & Travel",
    color: "#a66b16",
    soft: "#fbf1dc",
    icon: "map",
  },
  {
    id: "science",
    name: "科技探索",
    en: "Science & Tech",
    color: "#545b9b",
    soft: "#ececf7",
    icon: "flask-conical",
  },
  {
    id: "people",
    name: "成长与社会",
    en: "People & Society",
    color: "#8b4b63",
    soft: "#f6e9ee",
    icon: "users-round",
  },
  {
    id: "nature",
    name: "自然生命",
    en: "Living World",
    color: "#47702c",
    soft: "#edf3e7",
    icon: "leaf",
  },
];

const UNIT_CATALOG = [
  { key: "7A-U1", grade: "七年级", term: "上册", termKey: "7A", unit: 1, title: "Making friends", titleZh: "结交朋友" },
  { key: "7A-U2", grade: "七年级", term: "上册", termKey: "7A", unit: 2, title: "Daily life", titleZh: "日常生活" },
  { key: "7A-U3", grade: "七年级", term: "上册", termKey: "7A", unit: 3, title: "The Earth", titleZh: "地球" },
  { key: "7A-U4", grade: "七年级", term: "上册", termKey: "7A", unit: 4, title: "Seasons", titleZh: "季节" },
  { key: "7A-U5", grade: "七年级", term: "上册", termKey: "7A", unit: 5, title: "Visiting the Moon", titleZh: "参观月球" },
  { key: "7A-U6", grade: "七年级", term: "上册", termKey: "7A", unit: 6, title: "Travelling around Asia", titleZh: "亚洲之旅" },
  { key: "7A-U7", grade: "七年级", term: "上册", termKey: "7A", unit: 7, title: "School clubs", titleZh: "学校社团" },
  { key: "7A-U8", grade: "七年级", term: "上册", termKey: "7A", unit: 8, title: "Collecting things", titleZh: "收藏物品" },
  { key: "7B-U1", grade: "七年级", term: "下册", termKey: "7B", unit: 1, title: "People around us", titleZh: "我们身边的人" },
  { key: "7B-U2", grade: "七年级", term: "下册", termKey: "7B", unit: 2, title: "Travelling around the world", titleZh: "环游世界" },
  { key: "7B-U3", grade: "七年级", term: "下册", termKey: "7B", unit: 3, title: "Our animal friends", titleZh: "我们的动物朋友" },
  { key: "7B-U4", grade: "七年级", term: "下册", termKey: "7B", unit: 4, title: "Save the trees", titleZh: "拯救树木" },
  { key: "7B-U5", grade: "七年级", term: "下册", termKey: "7B", unit: 5, title: "Water", titleZh: "水" },
  { key: "7B-U6", grade: "七年级", term: "下册", termKey: "7B", unit: 6, title: "Electricity", titleZh: "电" },
  { key: "7B-U7", grade: "七年级", term: "下册", termKey: "7B", unit: 7, title: "Poems", titleZh: "诗歌" },
  { key: "7B-U8", grade: "七年级", term: "下册", termKey: "7B", unit: 8, title: "From hobby to career", titleZh: "从爱好到职业" },
  { key: "8A-U1", grade: "八年级", term: "上册", termKey: "8A", unit: 1, title: "Encyclopaedias", titleZh: "百科全书" },
  { key: "8A-U2", grade: "八年级", term: "上册", termKey: "8A", unit: 2, title: "Numbers", titleZh: "数字" },
  { key: "8A-U3", grade: "八年级", term: "上册", termKey: "8A", unit: 3, title: "Computers", titleZh: "电脑" },
  { key: "8A-U4", grade: "八年级", term: "上册", termKey: "8A", unit: 4, title: "Inventions", titleZh: "发明" },
  { key: "8A-U5", grade: "八年级", term: "上册", termKey: "8A", unit: 5, title: "Educational exchanges", titleZh: "教育交流" },
  { key: "8A-U6", grade: "八年级", term: "上册", termKey: "8A", unit: 6, title: "Ancient stories", titleZh: "古代故事" },
  { key: "8A-U7", grade: "八年级", term: "上册", termKey: "8A", unit: 7, title: "Memory", titleZh: "记忆" },
  { key: "8A-U8", grade: "八年级", term: "上册", termKey: "8A", unit: 8, title: "English Week", titleZh: "英语周" },
  { key: "8B-U1", grade: "八年级", term: "下册", termKey: "8B", unit: 1, title: "Helping those in need", titleZh: "帮助有需要的人" },
  { key: "8B-U2", grade: "八年级", term: "下册", termKey: "8B", unit: 2, title: "Body language", titleZh: "肢体语言" },
  { key: "8B-U3", grade: "八年级", term: "下册", termKey: "8B", unit: 3, title: "Traditional skills", titleZh: "传统技艺" },
  { key: "8B-U4", grade: "八年级", term: "下册", termKey: "8B", unit: 4, title: "Cartoons and comic strips", titleZh: "卡通与连环画" },
  { key: "8B-U5", grade: "八年级", term: "下册", termKey: "8B", unit: 5, title: "Save the endangered animals", titleZh: "拯救濒危动物" },
  { key: "8B-U6", grade: "八年级", term: "下册", termKey: "8B", unit: 6, title: "Pets", titleZh: "宠物" },
  { key: "8B-U7", grade: "八年级", term: "下册", termKey: "8B", unit: 7, title: "The unknown world", titleZh: "未知世界" },
  { key: "8B-U8", grade: "八年级", term: "下册", termKey: "8B", unit: 8, title: "Life in the future", titleZh: "未来生活" },
  { key: "9A-U1", grade: "九年级", term: "上册", termKey: "9A", unit: 1, title: "Wise men in history", titleZh: "历史上的智者" },
  { key: "9A-U2", grade: "九年级", term: "上册", termKey: "9A", unit: 2, title: "Great minds", titleZh: "伟大的思想家" },
  { key: "9A-U3", grade: "九年级", term: "上册", termKey: "9A", unit: 3, title: "Family life", titleZh: "家庭生活" },
  { key: "9A-U4", grade: "九年级", term: "上册", termKey: "9A", unit: 4, title: "Problems and advice", titleZh: "问题与建议" },
  { key: "9A-U5", grade: "九年级", term: "上册", termKey: "9A", unit: 5, title: "Action!", titleZh: "行动起来" },
  { key: "9A-U6", grade: "九年级", term: "上册", termKey: "9A", unit: 6, title: "Healthy diet", titleZh: "健康饮食" },
  { key: "9A-U7", grade: "九年级", term: "上册", termKey: "9A", unit: 7, title: "The Adventures of Tom Sawyer", titleZh: "汤姆·索亚历险记" },
  { key: "9A-U8", grade: "九年级", term: "上册", termKey: "9A", unit: 8, title: "Surprise endings", titleZh: "意外结局" },
  { key: "9B-U1", grade: "九年级", term: "下册", termKey: "9B", unit: 1, title: "Great explorations", titleZh: "伟大的探险" },
  { key: "9B-U2", grade: "九年级", term: "下册", termKey: "9B", unit: 2, title: "Culture shock", titleZh: "文化冲击" },
  { key: "9B-U3", grade: "九年级", term: "下册", termKey: "9B", unit: 3, title: "Environment", titleZh: "环境" },
  { key: "9B-U4", grade: "九年级", term: "下册", termKey: "9B", unit: 4, title: "Natural disasters", titleZh: "自然灾害" },
  { key: "9B-U5", grade: "九年级", term: "下册", termKey: "9B", unit: 5, title: "Sport", titleZh: "体育运动" },
  { key: "9B-U6", grade: "九年级", term: "下册", termKey: "9B", unit: 6, title: "Caring for your health", titleZh: "关注健康" },
];

const WORD_ROWS = [
  [
    "schedule",
    "/ˈʃedjuːl/",
    "/ˈskedʒuːl/",
    "n. / v.",
    "日程；时间表；安排",
    "I check my schedule every morning.",
    "我每天早上查看日程。",
    "sched·ule",
    "check the schedule|a busy schedule|according to schedule",
    "英音常读 /ˈʃedjuːl/，美音常读 /ˈskedʒuːl/；重音都在第一音节。",
    "campus",
    "七年级",
  ],
  [
    "subject",
    "/ˈsʌbdʒɪkt/",
    "/ˈsʌbdʒɪkt/",
    "n.",
    "学科；主题",
    "Science is my favourite subject.",
    "科学是我最喜欢的学科。",
    "sub·ject",
    "favourite subject|change the subject|main subject",
    "作名词时重音在前；作动词“使遭受”时重音在后 /səbˈdʒekt/。",
    "campus",
    "七年级",
  ],
  [
    "assignment",
    "/əˈsaɪnmənt/",
    "/əˈsaɪnmənt/",
    "n.",
    "作业；任务",
    "Finish the assignment before Friday.",
    "周五前完成这项作业。",
    "as·sign·ment",
    "finish an assignment|group assignment|written assignment",
    "末尾的 -ment 很轻，不要读成很重的“门特”。",
    "campus",
    "八年级",
  ],
  [
    "discussion",
    "/dɪˈskʌʃn/",
    "/dɪˈskʌʃn/",
    "n.",
    "讨论；商讨",
    "We had a discussion about city life.",
    "我们讨论了城市生活。",
    "dis·cus·sion",
    "have a discussion|group discussion|class discussion",
    "-sion 读 /ʃn/，重点在第二音节，结尾不要加元音。",
    "campus",
    "八年级",
  ],
  [
    "laboratory",
    "/ləˈbɒrətri/",
    "/ˈlæbrətɔːri/",
    "n.",
    "实验室",
    "The students are working in the laboratory.",
    "学生们正在实验室里做实验。",
    "la·bor·a·to·ry",
    "science laboratory|computer laboratory|in the laboratory",
    "美音常压缩为四个音节；两个口音的重音位置不同。",
    "campus",
    "九年级",
  ],
  [
    "knowledge",
    "/ˈnɒlɪdʒ/",
    "/ˈnɑːlɪdʒ/",
    "n.",
    "知识；学问",
    "Reading gives us knowledge.",
    "阅读给予我们知识。",
    "knowl·edge",
    "gain knowledge|a wide knowledge of|knowledge and skills",
    "k 不单独爆破；-edge 读 /ɪdʒ/，重音在第一音节。",
    "campus",
    "八年级",
  ],
  [
    "environment",
    "/ɪnˈvaɪrənmənt/",
    "/ɪnˈvaɪrənmənt/",
    "n.",
    "环境；自然环境",
    "We should protect the environment.",
    "我们应该保护环境。",
    "en·vi·ron·ment",
    "protect the environment|natural environment|environment-friendly",
    "重音在第二音节 /vaɪ/，中间的 r 要轻轻连过去。",
    "city",
    "八年级",
  ],
  [
    "pollution",
    "/pəˈluːʃn/",
    "/pəˈluːʃn/",
    "n.",
    "污染；污染物",
    "Air pollution is a serious problem.",
    "空气污染是一个严重问题。",
    "pol·lu·tion",
    "air pollution|reduce pollution|noise pollution",
    "重音在第二音节；-tion 固定常读 /ʃn/。",
    "city",
    "八年级",
  ],
  [
    "transport",
    "/ˈtrænspɔːt/",
    "/ˈtrænspɔːrt/",
    "n.",
    "交通运输；交通工具",
    "Public transport in Guangzhou is convenient.",
    "广州的公共交通很方便。",
    "trans·port",
    "public transport|transport system|air transport",
    "名词重音在前；作动词时英音可重读第二音节 /trænˈspɔːt/。",
    "city",
    "八年级",
  ],
  [
    "community",
    "/kəˈmjuːnəti/",
    "/kəˈmjuːnəti/",
    "n.",
    "社区；群体",
    "Our community has a new reading room.",
    "我们社区有了一个新阅读室。",
    "com·mu·ni·ty",
    "local community|community service|community centre",
    "重音在第二音节 /mjuː/，结尾 -ty 轻读。",
    "city",
    "九年级",
  ],
  [
    "ancient",
    "/ˈeɪnʃənt/",
    "/ˈeɪnʃənt/",
    "adj.",
    "古代的；古老的",
    "Guangzhou is an ancient city.",
    "广州是一座历史悠久的城市。",
    "an·cient",
    "ancient city|ancient culture|ancient times",
    "an- 读 /eɪn/；-cient 读 /ʃənt/，不要拆成两个重音。",
    "city",
    "八年级",
  ],
  [
    "modern",
    "/ˈmɒdn/",
    "/ˈmɑːdərn/",
    "adj.",
    "现代的；新式的",
    "Guangzhou has many modern buildings.",
    "广州有许多现代建筑。",
    "mod·ern",
    "modern city|modern technology|modern life",
    "英音常把中间 e 弱化；美音会清楚读出 /dər/。",
    "city",
    "七年级",
  ],
  [
    "exercise",
    "/ˈeksəsaɪz/",
    "/ˈeksərsaɪz/",
    "n. / v.",
    "锻炼；练习",
    "Regular exercise keeps us healthy.",
    "规律锻炼让我们保持健康。",
    "ex·er·cise",
    "take exercise|do exercises|regular exercise",
    "重音在第一音节；结尾 -cise 读 /saɪz/，不要读成 /siːz/。",
    "health",
    "七年级",
  ],
  [
    "healthy",
    "/ˈhelθi/",
    "/ˈhelθi/",
    "adj.",
    "健康的；有益健康的",
    "A balanced diet helps you stay healthy.",
    "均衡饮食帮助你保持健康。",
    "health·y",
    "keep healthy|healthy diet|a healthy lifestyle",
    "注意 /θ/：舌尖轻放在上下齿之间送出气流。",
    "health",
    "七年级",
  ],
  [
    "energy",
    "/ˈenədʒi/",
    "/ˈenərdʒi/",
    "n.",
    "精力；能量；能源",
    "Breakfast gives me energy for the day.",
    "早餐为我提供一天的能量。",
    "en·er·gy",
    "full of energy|save energy|clean energy",
    "第一个 e 是短音 /e/；g 在 -gy 中读 /dʒ/。",
    "health",
    "七年级",
  ],
  [
    "competition",
    "/ˌkɒmpəˈtɪʃn/",
    "/ˌkɑːmpəˈtɪʃn/",
    "n.",
    "比赛；竞争",
    "She entered a speech competition.",
    "她参加了一场演讲比赛。",
    "com·pe·ti·tion",
    "enter a competition|win a competition|a fair competition",
    "主重音在第三音节；-tion 读 /ʃn/。",
    "health",
    "八年级",
  ],
  [
    "champion",
    "/ˈtʃæmpiən/",
    "/ˈtʃæmpiən/",
    "n.",
    "冠军；拥护者",
    "Our team became the city champion.",
    "我们队成为了市冠军。",
    "cham·pi·on",
    "become a champion|national champion|team champion",
    "ch 读 /tʃ/；-ion 在这里是弱读的 /iən/。",
    "health",
    "八年级",
  ],
  [
    "balance",
    "/ˈbæləns/",
    "/ˈbæləns/",
    "n. / v.",
    "平衡；均衡",
    "Try to balance study and rest.",
    "尽量平衡学习和休息。",
    "bal·ance",
    "keep a balance|balanced diet|work-life balance",
    "a 读 /æ/，嘴巴要打开；结尾 -ance 弱读为 /əns/。",
    "health",
    "九年级",
  ],
  [
    "journey",
    "/ˈdʒɜːni/",
    "/ˈdʒɜːrni/",
    "n.",
    "旅行；行程",
    "The journey to the island takes two hours.",
    "去岛上的行程需要两小时。",
    "jour·ney",
    "a long journey|go on a journey|safe journey",
    "英音 /ɜː/ 不卷舌；美音 /ɜːr/ 要带清晰的 r 音。",
    "culture",
    "七年级",
  ],
  [
    "culture",
    "/ˈkʌltʃə(r)/",
    "/ˈkʌltʃər/",
    "n.",
    "文化；文化习俗",
    "Food is an important part of culture.",
    "饮食是文化的重要组成部分。",
    "cul·ture",
    "traditional culture|local culture|cultural difference",
    "cul- 读 /kʌl/；-ture 读 /tʃə(r)/，不要读成 /tuə/。",
    "culture",
    "八年级",
  ],
  [
    "traditional",
    "/trəˈdɪʃənl/",
    "/trəˈdɪʃənl/",
    "adj.",
    "传统的；惯例的",
    "Dim sum is a traditional Guangzhou food.",
    "点心是广州的传统食物。",
    "tra·di·tion·al",
    "traditional culture|traditional food|traditional festival",
    "重音在第二音节；-tion-al 连读为 /ʃənl/。",
    "culture",
    "八年级",
  ],
  [
    "festival",
    "/ˈfestɪvl/",
    "/ˈfestɪvl/",
    "n.",
    "节日；庆典",
    "The Spring Festival is coming.",
    "春节就要到了。",
    "fes·ti·val",
    "traditional festival|hold a festival|festival celebration",
    "重音在第一音节；-val 要轻，不要读满 /væl/。",
    "culture",
    "七年级",
  ],
  [
    "experience",
    "/ɪkˈspɪəriəns/",
    "/ɪkˈspɪriəns/",
    "n. / v.",
    "经历；经验；体验",
    "The trip was an unforgettable experience.",
    "这次旅行是一次难忘的经历。",
    "ex·pe·ri·ence",
    "learn from experience|work experience|a wonderful experience",
    "重音在第二音节；英音 /ɪə/ 更明显，美音常读 /ɪr/。",
    "culture",
    "八年级",
  ],
  [
    "destination",
    "/ˌdestɪˈneɪʃn/",
    "/ˌdestɪˈneɪʃn/",
    "n.",
    "目的地；终点",
    "Guangzhou is a popular tourist destination.",
    "广州是热门的旅游目的地。",
    "des·ti·na·tion",
    "tourist destination|reach the destination|final destination",
    "主重音在 -na- /neɪ/；-tion 读 /ʃn/。",
    "culture",
    "九年级",
  ],
  [
    "technology",
    "/tekˈnɒlədʒi/",
    "/tekˈnɑːlədʒi/",
    "n.",
    "科技；技术",
    "Technology changes the way we learn.",
    "科技改变我们的学习方式。",
    "tech·nol·o·gy",
    "modern technology|digital technology|technology company",
    "重音在第二音节；-nology 中的 o 弱读，g 读 /dʒ/。",
    "science",
    "八年级",
  ],
  [
    "invention",
    "/ɪnˈvenʃn/",
    "/ɪnˈvenʃn/",
    "n.",
    "发明；发明物",
    "Paper is an important Chinese invention.",
    "纸是中国的一项重要发明。",
    "in·ven·tion",
    "a great invention|the invention of|modern invention",
    "重音在第二音节；-tion 读 /ʃn/，不要多读一个音节。",
    "science",
    "九年级",
  ],
  [
    "digital",
    "/ˈdɪdʒɪtl/",
    "/ˈdɪdʒɪtl/",
    "adj.",
    "数字的；数码的",
    "We live in a digital world.",
    "我们生活在数字世界中。",
    "dig·i·tal",
    "digital world|digital device|digital learning",
    "di- 读 /dɪdʒ/；第二个 i 很轻，重音在第一音节。",
    "science",
    "八年级",
  ],
  [
    "experiment",
    "/ɪkˈsperɪmənt/",
    "/ɪkˈsperɪmənt/",
    "n. / v.",
    "实验；试验",
    "We did an experiment in class.",
    "我们在课堂上做了一个实验。",
    "ex·per·i·ment",
    "do an experiment|science experiment|experimental result",
    "重音在第二音节；最后一个 e 弱读，-ment 不要读得太重。",
    "science",
    "八年级",
  ],
  [
    "resource",
    "/rɪˈsɔːs/",
    "/ˈriːsɔːrs/",
    "n.",
    "资源；资料",
    "Water is a valuable natural resource.",
    "水是宝贵的自然资源。",
    "re·source",
    "natural resource|learning resource|limited resources",
    "英音常重读第二音节；部分美音重读第一音节 /ˈriːsɔːrs/。",
    "science",
    "九年级",
  ],
  [
    "communicate",
    "/kəˈmjuːnɪkeɪt/",
    "/kəˈmjuːnɪkeɪt/",
    "v.",
    "交流；沟通；传达",
    "We communicate with people around the world.",
    "我们与世界各地的人们交流。",
    "com·mu·ni·cate",
    "communicate with|communicate clearly|effective communication",
    "重音在第二音节；-cate 读 /keɪt/，结尾有轻微爆破。",
    "science",
    "八年级",
  ],
  [
    "volunteer",
    "/ˌvɒlənˈtɪə(r)/",
    "/ˌvɑːlənˈtɪr/",
    "n. / v.",
    "志愿者；自愿做",
    "Many students volunteer at the community centre.",
    "许多学生在社区中心做志愿服务。",
    "vol·un·teer",
    "volunteer work|volunteer to do|a student volunteer",
    "主重音在最后一个音节 /tɪə/ 或 /tɪr/。",
    "people",
    "九年级",
  ],
  [
    "responsibility",
    "/rɪˌspɒnsəˈbɪləti/",
    "/rɪˌspɑːnsəˈbɪləti/",
    "n.",
    "责任；职责",
    "Protecting the environment is our responsibility.",
    "保护环境是我们的责任。",
    "re·spon·si·bil·i·ty",
    "take responsibility|social responsibility|a sense of responsibility",
    "主重音在 -bil-；前后音节都要轻巧，单词较长但节奏要稳。",
    "people",
    "九年级",
  ],
  [
    "achieve",
    "/əˈtʃiːv/",
    "/əˈtʃiːv/",
    "v.",
    "实现；达到；取得",
    "You can achieve your goal with hard work.",
    "通过努力，你可以实现目标。",
    "a·chieve",
    "achieve a goal|achieve success|achieve high grades",
    "重音在第二音节；ch 读 /tʃ/，结尾 v 要有声带振动。",
    "people",
    "八年级",
  ],
  [
    "courage",
    "/ˈkʌrɪdʒ/",
    "/ˈkɜːrɪdʒ/",
    "n.",
    "勇气；勇敢",
    "It takes courage to speak in public.",
    "当众发言需要勇气。",
    "cour·age",
    "have the courage|take courage|show courage",
    "英音 /ʌ/ 更短；美音常读 /ɜːr/，重音都在第一音节。",
    "people",
    "九年级",
  ],
  [
    "respect",
    "/rɪˈspekt/",
    "/rɪˈspekt/",
    "n. / v.",
    "尊重；敬意",
    "We should respect different ideas.",
    "我们应该尊重不同的想法。",
    "re·spect",
    "show respect|respect others|mutual respect",
    "重音在第二音节；结尾 -ct 两个辅音都要收住。",
    "people",
    "八年级",
  ],
  [
    "opportunity",
    "/ˌɒpəˈtjuːnəti/",
    "/ˌɑːpərˈtuːnəti/",
    "n.",
    "机会；时机",
    "The exchange programme is a great opportunity.",
    "交流项目是一个很好的机会。",
    "op·por·tu·ni·ty",
    "a good opportunity|take the opportunity|equal opportunity",
    "主重音在 -tu-；英音常听到 /tjuː/，美音更常读 /tuː/。",
    "people",
    "九年级",
  ],
  [
    "creature",
    "/ˈkriːtʃə(r)/",
    "/ˈkriːtʃər/",
    "n.",
    "生物；动物",
    "This small creature lives near the river.",
    "这种小生物生活在河边。",
    "crea·ture",
    "living creature|wild creature|sea creature",
    "ea 读 /iː/；-ture 读 /tʃə(r)/。",
    "nature",
    "八年级",
  ],
  [
    "protect",
    "/prəˈtekt/",
    "/prəˈtekt/",
    "v.",
    "保护；防护",
    "We must protect wild animals.",
    "我们必须保护野生动物。",
    "pro·tect",
    "protect animals|protect from|protect the environment",
    "重音在第二音节；结尾 /kt/ 要收干净，不要加 /ə/。",
    "nature",
    "七年级",
  ],
  [
    "survive",
    "/səˈvaɪv/",
    "/sərˈvaɪv/",
    "v.",
    "生存；存活；挺过",
    "Some animals can survive in the desert.",
    "有些动物能在沙漠中生存。",
    "sur·vive",
    "survive in|survive the winter|survive a difficult time",
    "重音在第二音节；结尾 v 有振动，别和 f 混淆。",
    "nature",
    "八年级",
  ],
  [
    "species",
    "/ˈspiːʃiːz/",
    "/ˈspiːʃiːz/",
    "n.",
    "物种；种类",
    "Many species are in danger.",
    "许多物种正处于危险中。",
    "spe·cies",
    "endangered species|a species of|protect species",
    "单复数写法相同；-cies 读 /ʃiːz/。",
    "nature",
    "九年级",
  ],
  [
    "natural",
    "/ˈnætʃrəl/",
    "/ˈnætʃrəl/",
    "adj.",
    "自然的；天然的",
    "The park is a natural home for birds.",
    "这个公园是鸟类的自然家园。",
    "nat·u·ral",
    "natural world|natural resource|natural beauty",
    "ture 部分压缩成 /tʃr/；重音在第一音节。",
    "nature",
    "七年级",
  ],
  [
    "disappear",
    "/ˌdɪsəˈpɪə(r)/",
    "/ˌdɪsəˈpɪr/",
    "v.",
    "消失；灭绝；不见",
    "Many forests are disappearing quickly.",
    "许多森林正在迅速消失。",
    "dis·ap·pear",
    "disappear from|disappear quickly|make something disappear",
    "重音在最后音节；英音 /ɪə/ 要连滑，美音读 /ɪr/。",
    "nature",
    "八年级",
  ],
  [
    "friendly",
    "/ˈfrendli/",
    "/ˈfrendli/",
    "adj.",
    "友好的；亲切的",
    "Our new classmates are friendly to everyone.",
    "我们的新同学对每个人都很友好。",
    "friend·ly",
    "be friendly to|a friendly smile|friendly advice",
    "friend 与 -ly 连读，重音在第一音节。",
    "campus",
    "七年级",
  ],
  [
    "season",
    "/ˈsiːzn/",
    "/ˈsiːzn/",
    "n.",
    "季节",
    "Spring is my favourite season.",
    "春天是我最喜欢的季节。",
    "sea·son",
    "four seasons|rainy season|in season",
    "ea 读 /iː/，结尾 -son 弱读；不要多读一个 /o/。",
    "nature",
    "七年级",
  ],
  [
    "collection",
    "/kəˈlekʃn/",
    "/kəˈlekʃn/",
    "n.",
    "收藏品；收集",
    "My stamp collection is growing.",
    "我的邮票收藏正在增加。",
    "col·lec·tion",
    "a stamp collection|art collection|collection of",
    "重音在第二音节；-tion 常读 /ʃn/。",
    "campus",
    "七年级",
  ],
  [
    "poem",
    "/ˈpəʊɪm/",
    "/ˈpoʊəm/",
    "n.",
    "诗；诗歌",
    "We wrote a short poem about the sea.",
    "我们写了一首关于大海的短诗。",
    "po·em",
    "write a poem|a short poem|read a poem",
    "英音常读两个音节 /ˈpəʊɪm/；美音中间可弱化为 /ə/。",
    "culture",
    "七年级",
  ],
  [
    "career",
    "/kəˈrɪə(r)/",
    "/kəˈrɪr/",
    "n.",
    "职业；事业",
    "She wants a career in science.",
    "她想从事科学方面的职业。",
    "ca·reer",
    "career choice|a career in|start a career",
    "重音在第二音节；英音 /ɪə/ 与美音 /ɪr/ 要区分。",
    "people",
    "七年级",
  ],
  [
    "calculate",
    "/ˈkælkjuleɪt/",
    "/ˈkælkjuleɪt/",
    "v.",
    "计算；估算",
    "Let me calculate the total price.",
    "让我计算一下总价。",
    "cal·cu·late",
    "calculate the cost|calculate quickly|calculate from",
    "重音在第一音节；-late 读 /leɪt/，结尾有轻微爆破。",
    "science",
    "八年级",
  ],
  [
    "memory",
    "/ˈmeməri/",
    "/ˈmeməri/",
    "n.",
    "记忆；回忆",
    "The song brought back a happy memory.",
    "这首歌唤起了美好的回忆。",
    "mem·o·ry",
    "good memory|in memory of|memory skills",
    "重音在第一音节；第二个 o 弱读为 /ə/。",
    "campus",
    "八年级",
  ],
  [
    "cartoon",
    "/kɑːˈtuːn/",
    "/kɑːrˈtuːn/",
    "n.",
    "卡通片；漫画",
    "This cartoon is popular with teenagers.",
    "这部卡通片很受青少年欢迎。",
    "car·toon",
    "watch a cartoon|cartoon character|comic cartoon",
    "重音在第二音节；oo 读长音 /uː/。",
    "culture",
    "八年级",
  ],
  [
    "pet",
    "/pet/",
    "/pet/",
    "n.",
    "宠物",
    "Looking after a pet takes patience.",
    "照顾宠物需要耐心。",
    "pet",
    "keep a pet|pet care|a pet dog",
    "e 读短音 /e/，结尾 t 要收住，不能拖长。",
    "nature",
    "八年级",
  ],
  [
    "adventure",
    "/ədˈventʃə(r)/",
    "/ədˈventʃər/",
    "n.",
    "冒险；奇遇",
    "The story is full of adventure.",
    "这个故事充满冒险。",
    "ad·ven·ture",
    "a great adventure|go on an adventure|adventure story",
    "重音在第二音节；-ture 读 /tʃə(r)/。",
    "culture",
    "九年级",
  ],
  [
    "surprise",
    "/səˈpraɪz/",
    "/sərˈpraɪz/",
    "n. / v.",
    "惊喜；使惊讶",
    "The ending of the story is a surprise.",
    "故事的结局令人意外。",
    "sur·prise",
    "in surprise|a big surprise|surprise ending",
    "重音在第二音节；结尾 -prise 读 /praɪz/。",
    "culture",
    "九年级",
  ],
  [
    "explore",
    "/ɪkˈsplɔː(r)/",
    "/ɪkˈsplɔːr/",
    "v.",
    "探索；勘探",
    "People explore the unknown world with courage.",
    "人们带着勇气探索未知世界。",
    "ex·plore",
    "explore the world|explore an idea|explore space",
    "重音在第二音节；结尾 r 在英音中通常不卷。",
    "culture",
    "九年级",
  ],
];

const UNIT_BY_WORD = {
  schedule: "7A-U2",
  subject: "7A-U1",
  assignment: "7A-U2",
  discussion: "7A-U7",
  laboratory: "8A-U4",
  knowledge: "8A-U1",
  environment: "9B-U3",
  pollution: "7A-U3",
  transport: "8B-U8",
  community: "8B-U1",
  ancient: "8A-U6",
  modern: "9A-U2",
  exercise: "9B-U6",
  healthy: "9A-U6",
  energy: "7B-U6",
  competition: "9B-U5",
  champion: "9A-U5",
  balance: "9A-U6",
  journey: "7A-U5",
  culture: "9B-U2",
  traditional: "8B-U3",
  festival: "8A-U8",
  experience: "7B-U2",
  destination: "7A-U6",
  technology: "8A-U3",
  invention: "8A-U4",
  digital: "8A-U3",
  experiment: "9A-U1",
  resource: "7B-U5",
  communicate: "8B-U2",
  volunteer: "8B-U1",
  responsibility: "9A-U3",
  achieve: "7B-U8",
  courage: "9A-U4",
  respect: "7B-U1",
  opportunity: "8A-U5",
  creature: "7B-U3",
  protect: "7B-U4",
  survive: "8B-U7",
  species: "8B-U5",
  natural: "9B-U4",
  disappear: "8B-U5",
  friendly: "7A-U1",
  season: "7A-U4",
  collection: "7A-U8",
  poem: "7B-U7",
  career: "7B-U8",
  calculate: "8A-U2",
  memory: "8A-U7",
  cartoon: "8B-U4",
  pet: "8B-U6",
  adventure: "9A-U7",
  surprise: "9A-U8",
  explore: "9B-U1",
};

const unitCatalogMap = new Map(UNIT_CATALOG.map((unit) => [unit.key, unit]));

const WORDS = WORD_ROWS.map((row) => {
  const unit = unitCatalogMap.get(UNIT_BY_WORD[row[0]]);
  return {
    id: row[0],
    word: row[0],
    ipaUK: row[1],
    ipaUS: row[2],
    pos: row[3],
    meaning: row[4],
    example: row[5],
    exampleZh: row[6],
    syllables: row[7],
    collocations: row[8].split("|"),
    tip: row[9],
    topic: row[10],
    grade: unit?.grade || row[11],
    unitKey: unit?.key || "",
    termKey: unit?.termKey || "",
    termLabel: unit ? `${unit.grade.replace("年级", "")}${unit.term.replace("册", "")}` : "",
    unitNo: unit?.unit || 0,
    unitTitle: unit?.title || "",
    unitTitleZh: unit?.titleZh || "",
    unitLabel: unit ? `${unit.term} Unit ${unit.unit} · ${unit.title}` : "",
  };
});

const DAILY_PLAN = [
  "schedule",
  "environment",
  "exercise",
  "festival",
  "technology",
  "protect",
  "communicate",
  "opportunity",
];

const FOCUS_SOUNDS = [
  {
    ipa: "/θ/",
    label: "清齿擦音",
    hint: "舌尖轻放齿间，只送气",
    words: ["healthy"],
    contrast: "/s/",
    contrastHint: "healthy ≠ helsee",
  },
  {
    ipa: "/æ/",
    label: "前元音",
    hint: "嘴张大，舌位靠前",
    words: ["balance", "natural"],
    contrast: "/e/",
    contrastHint: "bad 与 bed 要分清",
  },
  {
    ipa: "/ɪ/",
    label: "短元音",
    hint: "短而放松，不要拖长",
    words: ["discussion", "pollution"],
    contrast: "/iː/",
    contrastHint: "ship 与 sheep 对照",
  },
  {
    ipa: "/tʃ/",
    label: "破擦音",
    hint: "先堵住，再送气",
    words: ["champion", "culture"],
    contrast: "/ʃ/",
    contrastHint: "chair 与 share 对照",
  },
];

window.APP_DATA = {
  topics: TOPICS,
  units: UNIT_CATALOG,
  words: WORDS,
  dailyPlan: DAILY_PLAN,
  focusSounds: FOCUS_SOUNDS,
};
